name: MARBLE
channels:
  - pyg
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.5=py39h67323c0_0
  - brotli=1.0.9=hca72f7f_7
  - brotli-bin=1.0.9=hca72f7f_7
  - brotlipy=0.7.0=py39h9ed2024_1003
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2022.07.19=hecd8cb5_0
  - certifi=2022.9.24=py39hecd8cb5_0
  - cffi=1.15.1=py39hc55c11b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=37.0.1=py39hf6deb26_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=0.29.32=py39he9d5cce_0
  - ffmpeg=4.3=h0a44026_0
  - fftw=3.3.9=h9ed2024_1
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=hd8bbffd_0
  - gettext=0.21.0=h7535e17_0
  - giflib=5.2.1=haf1e3a3_0
  - gmp=6.2.1=he9d5cce_3
  - gnutls=3.6.15=hed9c0bf_0
  - icu=58.2=h0a44026_3
  - idna=3.4=py39hecd8cb5_0
  - intel-openmp=2021.4.0=hecd8cb5_3538
  - jinja2=3.0.3=pyhd3eb1b0_0
  - joblib=1.1.1=py39hecd8cb5_0
  - jpeg=9e=hca72f7f_0
  - kiwisolver=1.4.2=py39he9d5cce_0
  - lame=3.100=h1de35cc_0
  - lapack=3.9.0=netlib
  - lcms2=2.12=hf1fd2bf_0
  - lerc=3.0=he9d5cce_0
  - libblas=3.9.0=12_osx64_mkl
  - libbrotlicommon=1.0.9=hca72f7f_7
  - libbrotlidec=1.0.9=hca72f7f_7
  - libbrotlienc=1.0.9=hca72f7f_7
  - libcxx=14.0.6=h9765a3e_0
  - libdeflate=1.8=h9ed2024_5
  - libffi=3.3=hb1e8313_2
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libiconv=1.16=hca72f7f_2
  - libidn2=2.3.2=h9ed2024_0
  - liblapack=3.9.0=12_osx64_mkl
  - libpng=1.6.37=ha441bb4_0
  - libprotobuf=3.20.1=h8346a28_0
  - libtasn1=4.16.0=h9ed2024_0
  - libtiff=4.4.0=h2ef1027_0
  - libunistring=0.9.10=h9ed2024_0
  - libwebp=1.2.4=h56c3ce4_0
  - libwebp-base=1.2.4=hca72f7f_0
  - libxml2=2.9.14=hbf8cd5e_0
  - llvm-openmp=14.0.6=h0dcd299_0
  - lz4-c=1.9.3=h23ab428_1
  - markupsafe=2.1.1=py39hca72f7f_0
  - matplotlib=3.5.2=py39hecd8cb5_0
  - matplotlib-base=3.5.2=py39hfb0c5b7_0
  - mkl=2021.4.0=hecd8cb5_637
  - mkl-service=2.4.0=py39h9ed2024_0
  - mkl_fft=1.3.1=py39h4ab4a9b_0
  - mkl_random=1.2.2=py39hb2f4e1b_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=hca72f7f_3
  - nettle=3.7.3=h230ac6f_1
  - networkx=2.8.4=py39hecd8cb5_0
  - numexpr=2.8.3=py39h2e5f0a9_0
  - numpy=1.23.3=py39hce7a837_0
  - numpy-base=1.23.3=py39heddfccc_0
  - openh264=2.1.1=h8346a28_0
  - openssl=1.1.1q=hca72f7f_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.4=py39he9d5cce_0
  - pillow=9.2.0=py39hde71d04_1
  - pip=22.2.2=py39hecd8cb5_0
  - pot=0.8.2=py39hca71b8a_1
  - protobuf=3.20.1=py39he9d5cce_0
  - pybind11=2.9.2=py39hc29d2bd_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyg=2.1.0=py39_torch_1.12.0_cpu
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py39hecd8cb5_0
  - pysocks=1.7.1=py39hecd8cb5_0
  - python=3.9.13=hdfd78df_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=1.12.1=py3.9_0
  - pytorch-cluster=1.6.0=py39_torch_1.12.0_cpu
  - pytorch-scatter=2.0.9=py39_torch_1.12.0_cpu
  - pytorch-sparse=0.6.15=py39_torch_1.12.0_cpu
  - pytz=2022.1=py39hecd8cb5_0
  - pyyaml=6.0=py39hca72f7f_1
  - readline=8.1.2=hca72f7f_1
  - requests=2.28.1=py39hecd8cb5_0
  - scikit-learn=1.1.2=py39he9d5cce_0
  - scipy=1.9.1=py39h3d31255_0
  - seaborn=0.12.0=py39hecd8cb5_0
  - setuptools=63.4.1=py39hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.3=h707629a_0
  - tensorboardx=2.2=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h5d9f67b_0
  - torchaudio=0.12.1=py39_cpu
  - torchvision=0.13.1=py39_cpu
  - tornado=6.2=py39hca72f7f_0
  - tqdm=4.64.1=py39hecd8cb5_0
  - typing_extensions=4.3.0=py39hecd8cb5_0
  - tzdata=2022e=h04d1e81_0
  - urllib3=1.26.12=py39hecd8cb5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=hca72f7f_0
  - yaml=0.2.5=haf1e3a3_0
  - zlib=1.2.12=h4dc903c_3
  - zstd=1.5.2=hcb37349_0
  - pip:
    - teaspoon==1.3.1
    - umap==0.1.1