name: MARBLE
channels:
  - pytorch
  - pyg
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.5=py39h080aedc_0
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotlipy=0.7.0=py39h2bbff1b_1003
  - ca-certificates=2023.08.22=haa95532_0
  - certifi=2023.7.22=py39haa95532_0
  - cffi=1.15.1=py39h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=py39haa95532_0
  - contourpy=1.0.5=py39h59b6b97_0
  - cryptography=41.0.3=py39h89fc84f_0
  - cudatoolkit=11.3.1=h59b6b97_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - giflib=5.2.1=h8cc25b3_3
  - glib=2.69.1=h5dc1a3c_2
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.4=py39haa95532_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2023.1.0=h59b6b97_46319
  - jinja2=3.1.2=py39haa95532_0
  - joblib=1.2.0=py39haa95532_0
  - jpeg=9e=h2bbff1b_1
  - kiwisolver=1.4.4=py39hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - lerc=3.0=hd77b12b_0
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_0
  - libiconv=1.16=h2bbff1b_2
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.15=h906ac69_1
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - libxml2=2.10.4=h0ad7f3c_1
  - libxslt=1.1.37=h2bbff1b_1
  - lz4-c=1.9.4=h2bbff1b_0
  - markupsafe=2.1.1=py39h2bbff1b_0
  - matplotlib=3.7.2=py39haa95532_0
  - matplotlib-base=3.7.2=py39h4ed8f06_0
  - mkl=2023.1.0=h6b88ed4_46357
  - mkl-service=2.4.0=py39h2bbff1b_1
  - mkl_fft=1.3.8=py39h2bbff1b_0
  - mkl_random=1.2.4=py39h59b6b97_0
  - munkres=1.1.4=py_0
  - networkx=3.1=py39haa95532_0
  - numexpr=2.8.7=py39h2cd9be0_0
  - numpy=1.26.0=py39h055cbcc_0
  - numpy-base=1.26.0=py39h65a83cf_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=3.0.11=h2bbff1b_2
  - packaging=23.1=py39haa95532_0
  - pandas=2.1.1=py39h4ed8f06_0
  - pcre=8.45=hd77b12b_0
  - pillow=10.0.1=py39h045eedc_0
  - pip=23.3=py39haa95532_0
  - ply=3.11=py39haa95532_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyg=2.1.0=py39_torch_1.12.0_cu113
  - pyopenssl=23.2.0=py39haa95532_0
  - pyparsing=3.0.9=py39haa95532_0
  - pyqt=5.15.7=py39hd77b12b_0
  - pyqt5-sip=12.11.0=py39hd77b12b_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.18=h1aa4202_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytorch=1.12.1=py3.9_cuda11.3_cudnn8_0
  - pytorch-cluster=1.6.0=py39_torch_1.12.0_cu113
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.0.9=py39_torch_1.12.0_cu113
  - pytorch-sparse=0.6.15=py39_torch_1.12.0_cu113
  - pytz=2023.3.post1=py39haa95532_0
  - qt-main=5.15.2=h879a1e9_9
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtwebkit=5.212=h2bbfb41_5
  - requests=2.31.0=py39haa95532_0
  - scikit-learn=1.3.0=py39h4ed8f06_0
  - scipy=1.11.3=py39h309d312_0
  - setuptools=68.0.0=py39haa95532_0
  - sip=6.6.2=py39hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchaudio=0.12.1=py39_cu113
  - torchvision=0.13.1=py39_cu113
  - tornado=6.3.3=py39h2bbff1b_0
  - tqdm=4.65.0=py39hd4e2768_0
  - typing_extensions=4.7.1=py39haa95532_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py39haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.41.2=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - xz=5.4.2=h8cc25b3_0
  - zipp=3.11.0=py39haa95532_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - teaspoon==1.3.1
