name: state_space_embedding
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aom=3.4.0=h27087fc_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.07.19=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - conda-pack=0.6.0=pyhd3eb1b0_0
  - cuda-nvcc=11.3.58=h2467b9f_0
  - cudatoolkit=11.3.1=ha36c431_9
  - cudnn=8.2.1.32=h86fa8c9_0
  - freetype=2.10.4=h0708190_1
  - geos=3.9.1=h9c3ff4c_2
  - gettext=0.19.8.1=h73d1719_1008
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.7.6=hf3e180e_5
  - h5py=3.1.0=nompi_py37h1e651dc_100
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - icu=70.1=h27087fc_0
  - jpeg=9e=h166bdaf_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=15_linux64_openblas
  - libcblas=3.9.0=15_linux64_openblas
  - libcurl=7.83.1=h7bff187_0
  - libdeflate=1.10=h7f98852_0
  - libdrm=2.4.111=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.2=h7f98852_0
  - liblapack=3.9.0=15_linux64_openblas
  - libnghttp2=1.47.0=h727a467_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libpciaccess=0.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtasn1=4.18.0=h166bdaf_1
  - libtiff=4.3.0=h0fcbabc_4
  - libunistring=0.9.10=h7f98852_0
  - libva=2.14.0=h7f98852_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.14=h22db469_0
  - libzlib=1.2.12=h166bdaf_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - ncurses=6.3=h27087fc_1
  - nettle=3.8=hc379101_0
  - numpy=1.19.5=py37h3e96413_3
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.2.0=h6239696_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1q=h7f8727e_0
  - p11-kit=0.24.1=hc5aa10d_0
  - pandas=1.3.5=py37he8f5f7f_0
  - pillow=8.4.0=py37h0f21c89_0
  - pip=22.0.3=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - python=3.7.12=hb7a2778_100_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pytz=2022.1=pyhd8ed1ab_0
  - readline=8.1.2=h0f457ee_0
  - scipy=1.7.3=py37hf2a6cf1_0
  - setuptools=59.8.0=py37h89c1867_1
  - shapely=1.7.1=py37h48c49eb_5
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.39.0=h4ff8645_0
  - svt-av1=1.1.0=h27087fc_1
  - tk=8.6.12=h27826a3_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - zlib=1.2.12=h166bdaf_1
  - zstd=1.5.2=h8a70e8d_1
  - pip:
    - absl-py==0.15.0
    - anyio==3.6.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - astunparse==1.6.3
    - attrs==21.2.0
    - babel==2.10.3
    - backcall==0.2.0
    - backports-zoneinfo==0.2.1
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - cachetools==4.2.4
    - cattrs==1.1.1
    - certifi==2021.10.8
    - cffi==1.15.1
    - charset-normalizer==2.0.12
    - cknn==0.1.0
    - clang==5.0
    - colorama==0.4.4
    - commonmark==0.9.1
    - cycler==0.11.0
    - cython==0.29.32
    - de-library==1.0
    - debugpy==1.6.2
    - decorator==5.1.1
    - defusedxml==0.7.1
    - efficientnet==1.0.0
    - entrypoints==0.4
    - fastjsonschema==2.16.1
    - flatbuffers==1.12
    - fonttools==4.33.3
    - gast==0.4.0
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.44.0
    - idna==3.3
    - image-classifiers==1.0.0
    - imageio==2.15.0
    - imgaug==0.4.0
    - imgstore==0.2.9
    - importlib-metadata==4.11.1
    - importlib-resources==5.9.0
    - ipykernel==6.15.1
    - ipython==7.34.0
    - ipython-genutils==0.2.0
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - jsmin==3.0.1
    - json5==0.9.8
    - jsonpickle==1.2
    - jsonschema==4.8.0
    - jupyter-client==7.3.4
    - jupyter-core==4.11.1
    - jupyter-server==1.18.1
    - jupyterlab==3.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.15.0
    - keras==2.6.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.2
    - markdown==3.3.6
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - nbclassic==0.4.3
    - nbclient==0.6.6
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - networkx==2.6.3
    - notebook==6.4.12
    - notebook-shim==0.1.0
    - oauthlib==3.2.0
    - opencv-python==4.5.5.62
    - opencv-python-headless==4.5.5.62
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pot==0.8.2
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.30
    - protobuf==3.19.4
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.10.0
    - pycparser==2.21
    - pyedm==1.13.1.0
    - pygments==2.12.0
    - pykalman==0.9.5
    - pyparsing==3.0.6
    - pyrsistent==0.18.1
    - pyside2==5.14.1
    - python-rapidjson==1.6
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.3.0
    - pyzmq==23.2.0
    - qimage2ndarray==1.8.3
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rich==10.16.1
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - scikit-video==1.1.11
    - seaborn==0.11.2
    - segmentation-models==1.0.1
    - send2trash==1.8.0
    - setuptools-scm==6.3.2
    - shiboken2==5.14.1
    - sklearn==0.0
    - sleap==1.2.3
    - sniffio==1.2.0
    - soupsieve==2.3.2.post1
    - teaspoon==1.3.1
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - tensorflow==2.6.3
    - tensorflow-estimator==2.6.0
    - termcolor==1.1.0
    - terminado==0.15.0
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - tinycss2==1.1.1
    - tomli==2.0.1
    - torch==1.12.1
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.3.0
    - typing-extensions==3.10.0.2
    - tzdata==2022.1
    - tzlocal==4.2
    - urllib3==1.26.8
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.3.3
    - werkzeug==2.0.3
    - wrapt==1.12.1
    - zipp==3.7.0
prefix: /mnt/scratch/lts2/gosztolai/miniconda3/envs/sleap
